// DO NOT MANUALLY EDIT THIS FILE. IT IS AUTO-GENERATED BY FIREBASE STUDIO.
'use client';
import React, {createContext, useContext, useMemo} from 'react';
import type {FirebaseApp} from 'firebase/app';
import {getAuth, type Auth} from 'firebase/auth';
import {getFirestore, type Firestore} from 'firebase/firestore';
import {FirebaseProvider, initializeFirebase} from '@/firebase';

/** `FirebaseClientProvider` provides the initialized firebase app and services to its children.
 * It ensures that firebase is initialized only once on the client.
 * Children of this provider can use the `useFirebaseApp`, `useAuth`, and `useFirestore` hooks to access the firebase app and services.
 *
 * It is recommended to wrap the root layout of your application with this provider.
 */
export function FirebaseClientProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const {firebaseApp, auth, firestore} = useMemo(() => {
    const app = initializeFirebase();
    const auth = getAuth(app);
    const firestore = getFirestore(app);
    return {firebaseApp: app, auth, firestore};
  }, []);

  return (
    <FirebaseProvider
      firebaseApp={firebaseApp}
      auth={auth}
      firestore={firestore}
    >
      {children}
    </FirebaseProvider>
  );
}
