// DO NOT MANUALLY EDIT THIS FILE. IT IS AUTO-GENERATED BY FIREBASE STUDIO.
import type {FirebaseOptions} from 'firebase/app';

/**
 * The Firebase project configuration object.
 *
 * This configuration is used to initialize the Firebase app.
 * It is automatically generated by Firebase Studio based on your project.
 */
export const firebaseConfig: FirebaseOptions = {
  "projectId": "studio-5563908398-ecf4f",
  "appId": "1:793313787285:web:4c1cb45b68f5cff9e48a9c",
  "apiKey": "AIzaSyAeT3QKraTTX0sXmUYHsQanRd65GinFfFM",
  "authDomain": "studio-5563908398-ecf4f.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "793313787285",
  "storageBucket": "studio-5563908398-ecf4f.appspot.com"
};
