// DO NOT MANUALLY EDIT THIS FILE. IT IS AUTO-GENERATED BY FIREBASE STUDIO.
import type {FirebaseOptions} from 'firebase/app';

/**
 * The Firebase project configuration object.
 *
 * This configuration is used to initialize the Firebase app.
 * It is automatically generated by Firebase Studio based on your project.
 */
export const firebaseConfig: FirebaseOptions = {
  "apiKey": "API_KEY",
  "authDomain": "AUTH_DOMAIN",
  "projectId": "PROJECT_ID",
  "storageBucket": "STORAGE_BUCKET",
  "messagingSenderId": "MESSAGING_SENDER_ID",
  "appId": "APP_ID",
  "measurementId": "MEASUREMENT_ID"
};
