// DO NOT MANUALLY EDIT THIS FILE. IT IS AUTO-GENERATED BY FIREBASE STUDIO.
export type SecurityRuleContext = {
  path: string;
  operation: 'get' | 'list' | 'create' | 'update' | 'delete';
  requestResourceData?: any;
};

export class FirestorePermissionError extends Error {
  constructor(public context: SecurityRuleContext) {
    const operation = context.operation.toUpperCase();
    const path = context.path;

    const message = `Firestore Permission Error: ${operation} on ${path}`;

    super(message);
    this.name = 'FirestorePermissionError';
  }

  toString(): string {
    const operation = this.context.operation.toUpperCase();
    const path = this.context.path;

    let message = `The following request was denied by Firestore Security Rules:\n`;
    message += `  - Operation: ${operation}\n`;
    message += `  - Path: ${path}\n`;

    if (this.context.requestResourceData) {
      const resource = JSON.stringify(this.context.requestResourceData, null, 2)
        .split('\n')
        .map(line => `  ${line}`)
        .join('\n');
      message += `  - Request Data:\n${resource}\n`;
    }

    return message;
  }
}
